contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #liverctanalysis channel"
    url: https://nfcore.slack.com/channels/liverctanalysis
    about: Discussion about the nf-core/liverctanalysis pipeline
