name: liver_ct_seg_pkg
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - defaults::cudatoolkit=11.0.221
  - defaults::python=3.8.2
  - conda-forge::tensorboardx=2.1
  - conda-forge::mlflow=1.13.1
  - conda-forge::rich=9.10.0
  - pytorch::pytorch=1.7.1
  - pytorch::torchvision=0.8.2
  - pytorch-lightning==1.1.8
  - mrcfile=1.3.0=pyh44b312d_0
  - pip
  - pip:
      - pycuda==2019.1.2 # not on Conda
      - cloudpickle==1.6.0
      - boto3==1.17.7
      - system-intelligence==2.0.2
      - liver-ct-segmentation-package==1.6.0
